**Task-1 :Data understanding and preprocessing**

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
data=pd.read_csv("/content/drive/MyDrive/data science (1)/used_device_data.csv")
data

device_brand       os  screen_size   4g   5g  rear_camera_mp  \
0           Honor  Android        14.50  yes   no            13.0   
1           Honor  Android        17.30  yes  yes            13.0   
2           Honor  Android        16.69  yes  yes            13.0   
3           Honor  Android        25.50  yes  yes            13.0   
4           Honor  Android        15.32  yes   no            13.0   
...           ...      ...          ...  ...  ...             ...   
3449         Asus  Android        15.34  yes   no             NaN   
3450         Asus  Android        15.24  yes   no            13.0   
3451      Alcatel  Android        15.80  yes   no            13.0   
3452      Alcatel  Android        15.80  yes   no            13.0   
3453      Alcatel  Android        12.83  yes   no            13.0   

      front_camera_mp  internal_memory  ram  battery  weight  release_year  \
0                 5.0             64.0  3.0   3020.0   146.0          2020   
1                16.0            128.0  8.0   4300.0   213.0          2020   
2                 8.0            128.0  8.0   4200.0   213.0          2020   
3                 8.0             64.0  6.0   7250.0   480.0          2020   
4                 8.0             64.0  3.0   5000.0   185.0          2020   
...               ...              ...  ...      ...     ...           ...   
3449              8.0             64.0  6.0   5000.0   190.0          2019   
3450              8.0            128.0  8.0   4000.0   200.0          2018   
3451              5.0             32.0  3.0   4000.0   165.0          2020   
3452              5.0             32.0  2.0   4000.0   160.0          2020   
3453              5.0             16.0  2.0   4000.0   168.0          2020   

      days_used  normalized_used_price  normalized_new_price  
0           127               4.307572              4.715100  
1           325               5.162097              5.519018  
2           162               5.111084              5.884631  
3           345               5.135387              5.630961  
4           293               4.389995              4.947837  
...         ...                    ...                   ...  
3449        232               4.492337              6.483872  
3450        541               5.037732              6.251538  
3451        201               4.357350              4.528829  
3452        149               4.349762              4.624188  
3453        176               4.132122              4.279994  

[3454 rows x 15 columns]

In [ ]:
data.isna().sum()

device_brand               0
os                         0
screen_size                0
4g                         0
5g                         0
rear_camera_mp           179
front_camera_mp            2
internal_memory            4
ram                        4
battery                    6
weight                     7
release_year               0
days_used                  0
normalized_used_price      0
normalized_new_price       0
dtype: int64

In [ ]:
data["internal_memory"].fillna(data["internal_memory"].mean(), inplace=True)
data["front_camera_mp"].fillna(data["front_camera_mp"].mean(), inplace=True)
data["ram"].fillna(data["ram"].mean(), inplace=True)
data["battery"].fillna(data["battery"].mean(), inplace=True)
data["weight"].fillna(data["weight"].mean(), inplace=True)


/tmp/ipython-input-3690720856.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["internal_memory"].fillna(data["internal_memory"].mean(), inplace=True)
/tmp/ipython-input-3690720856.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(v

In [ ]:
data.isna().sum()

device_brand               0
os                         0
screen_size                0
4g                         0
5g                         0
rear_camera_mp           179
front_camera_mp            0
internal_memory            0
ram                        0
battery                    0
weight                     0
release_year               0
days_used                  0
normalized_used_price      0
normalized_new_price       0
dtype: int64

In [ ]:
data1=data.drop(["rear_camera_mp"],axis=1)
data1

device_brand       os  screen_size   4g   5g  front_camera_mp  \
0           Honor  Android        14.50  yes   no              5.0   
1           Honor  Android        17.30  yes  yes             16.0   
2           Honor  Android        16.69  yes  yes              8.0   
3           Honor  Android        25.50  yes  yes              8.0   
4           Honor  Android        15.32  yes   no              8.0   
...           ...      ...          ...  ...  ...              ...   
3449         Asus  Android        15.34  yes   no              8.0   
3450         Asus  Android        15.24  yes   no              8.0   
3451      Alcatel  Android        15.80  yes   no              5.0   
3452      Alcatel  Android        15.80  yes   no              5.0   
3453      Alcatel  Android        12.83  yes   no              5.0   

      internal_memory  ram  battery  weight  release_year  days_used  \
0                64.0  3.0   3020.0   146.0          2020        127   
1               128.0  8.0   4300.0   213.0          2020        325   
2               128.0  8.0   4200.0   213.0          2020        162   
3                64.0  6.0   7250.0   480.0          2020        345   
4                64.0  3.0   5000.0   185.0          2020        293   
...               ...  ...      ...     ...           ...        ...   
3449             64.0  6.0   5000.0   190.0          2019        232   
3450            128.0  8.0   4000.0   200.0          2018        541   
3451             32.0  3.0   4000.0   165.0          2020        201   
3452             32.0  2.0   4000.0   160.0          2020        149   
3453             16.0  2.0   4000.0   168.0          2020        176   

      normalized_used_price  normalized_new_price  
0                  4.307572              4.715100  
1                  5.162097              5.519018  
2                  5.111084              5.884631  
3                  5.135387              5.630961  
4                  4.389995              4.947837  
...                     ...                   ...  
3449               4.492337              6.483872  
3450               5.037732              6.251538  
3451               4.357350              4.528829  
3452               4.349762              4.624188  
3453               4.132122              4.279994  

[3454 rows x 14 columns]

In [ ]:
data1.isna().sum()

device_brand             0
os                       0
screen_size              0
4g                       0
5g                       0
front_camera_mp          0
internal_memory          0
ram                      0
battery                  0
weight                   0
release_year             0
days_used                0
normalized_used_price    0
normalized_new_price     0
dtype: int64

In [ ]:
data1.dtypes

device_brand              object
os                        object
screen_size              float64
4g                        object
5g                        object
front_camera_mp          float64
internal_memory          float64
ram                      float64
battery                  float64
weight                   float64
release_year               int64
days_used                  int64
normalized_used_price    float64
normalized_new_price     float64
dtype: object

In [ ]:
from sklearn import preprocessing

In [ ]:
lb=preprocessing.LabelEncoder()
data1["device_brand"]=lb.fit_transform(data1["device_brand"])
data1["device_brand"].unique()


array([10, 24,  9, 11, 12, 15, 16, 14, 17, 18, 20, 21, 22, 23, 26, 27, 30,
       32, 33,  2,  3,  6,  0,  1,  4,  5,  7,  8, 13, 19, 25, 28, 29, 31])

In [ ]:
lb=preprocessing.LabelEncoder()
data1["os"]=lb.fit_transform(data1["os"])
data1["os"].unique()


array([0, 1, 3, 2])

In [ ]:
lb=preprocessing.LabelEncoder()
data1["4g"]=lb.fit_transform(data1["4g"])
data1["4g"].unique()

array([1, 0])

In [ ]:
lb=preprocessing.LabelEncoder()
data1["5g"]=lb.fit_transform(data1["5g"])
data1["5g"].unique()

array([0, 1])

In [ ]:
data1.drop(["normalized_new_price"],axis=1,inplace=True)


In [ ]:
data1.dtypes

device_brand               int64
os                         int64
screen_size              float64
4g                         int64
5g                         int64
front_camera_mp          float64
internal_memory          float64
ram                      float64
battery                  float64
weight                   float64
release_year               int64
days_used                  int64
normalized_used_price    float64
dtype: object

**Task 2:Model building**

**Deep learning-CNN**

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

In [ ]:
model=Sequential()

model.add(Conv2D(32,(3,3),activation="relu",input_shape=(64,64,3)))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(64,(3,3),activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(128,activation="relu"))
model.add(Dense(1,activation="sigmoid"))


/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])


In [ ]:
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 62, 62, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 31, 31, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 29, 29, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 14, 14, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 12544)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │     1,605,760 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,625,281 (6.20 MB)

 Trainable params: 1,625,281 (6.20 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
import tensorflow as tf

IMG_SIZE =(64,64)
BATCH_SIZE =32
train_dataset=tf.keras.utils.image_dataset_from_directory("/content/drive/MyDrive/ml dataset/dataset-20250410T042537Z-001/dataset/training_set",image_size=IMG_SIZE,batch_size=BATCH_SIZE)
test_dataset=tf.keras.utils.image_dataset_from_directory("/content/drive/MyDrive/ml dataset/dataset-20250410T042537Z-001/dataset/test_set",image_size=IMG_SIZE,batch_size=BATCH_SIZE)


Found 53 files belonging to 2 classes.
Found 53 files belonging to 2 classes.


In [ ]:
model.fit(train_dataset, epochs=10, validation_data=test_dataset)



Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 19s 11s/step - accuracy: 0.4959 - loss: 146.9170 - val_accuracy: 0.5472 - val_loss: 257.9924
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 423ms/step - accuracy: 0.5002 - loss: 257.9783 - val_accuracy: 0.5849 - val_loss: 4.1216
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 360ms/step - accuracy: 0.5145 - loss: 12.4591 - val_accuracy: 0.4528 - val_loss: 29.9837
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 384ms/step - accuracy: 0.4373 - loss: 27.9098 - val_accuracy: 0.4528 - val_loss: 10.4622
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 388ms/step - accuracy: 0.4477 - loss: 8.4681 - val_accuracy: 0.5472 - val_loss: 3.6485
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 404ms/step - accuracy: 0.5419 - loss: 4.0698 - val_accuracy: 0.5472 - val_loss: 4.4237
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 389ms/step - accuracy: 0.5523 - loss: 4.0043 - val_accuracy: 0.5472 - val_loss: 2.1189
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 598ms/step - accuracy: 0.5419 - loss: 1.9997 - val_accuracy: 0.6226 - 

1.why this model was choosen?

images have spatial structure.
CNNs automatically extract features like edges, shapes, and textures.
fewer parameters than fully connected networks.
high performance in image classification tasks.

2.How features impact prediction?

early layers detect edges,corners.
middle layers used for shapes,textures.
deeper layers uded for object specific patterns(ears, faces).
good features causes higher accuracy.
poor features causes for misclassification.

3.what improvements can be done?

add more Conv layers.
increase filters.
use Batch Normalization.
add Dropout to reduce overfitting.


In [ ]:
model.save("cnn_model.h5")

In [ ]:
from google.colab import files
files.download("cnn_model.h5")


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>